<a href="https://www.kaggle.com/code/sagorkumarmitra/numpy-walkthrough?scriptVersionId=140339782" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np

# The N-dimensional array (ndarray)

**A 2-dimensional array of size 2 x 3, composed of 4-byte integer elements:**

In [2]:
x=np.array([[1,2,3],[4,5,6]],np.int32)

In [3]:
type(x)

numpy.ndarray

In [4]:
x.shape

(2, 3)

In [5]:
x.dtype

dtype('int32')

In [6]:
x[1,2]

6

In [7]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [8]:
y=x[:,1]

In [9]:
y

array([2, 5], dtype=int32)

In [10]:
y[0]=9

**Memory layout**

In [11]:
x #ndarray

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [12]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [13]:
x.shape

(2, 3)

In [14]:
x.strides

(12, 4)

In [15]:
x.ndim

2

In [16]:
x.data

In [17]:
x.size

6

In [18]:
x.itemsize

4

In [19]:
x.nbytes

24

In [20]:
x.base

In [21]:
x.dtype

dtype('int32')

In [22]:
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [23]:
x.T

array([[1, 4],
       [9, 5],
       [3, 6]], dtype=int32)

In [24]:
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [25]:
x.real

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [26]:
x.imag

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [27]:
x.flat

In [28]:
x.ctypes

In [29]:
x.tolist()

[[1, 9, 3], [4, 5, 6]]

In [30]:
x.copy()

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [31]:
x.view()

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [32]:
x.fill(0)

In [33]:
x

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [34]:
x=np.array([[1,2,3],[4,5,6],[5,6,7]],np.int32)

**A 3-dimensional array of size 3 x 3 x 3, summed over each of its three axes**

In [35]:
x=np.arange(27)

In [36]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [37]:
x=np.arange(27).reshape(3,3,3)

In [38]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [39]:
x.sum(axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [40]:
x.sum(0),x.sum(1),x.sum(2)

(array([[27, 30, 33],
        [36, 39, 42],
        [45, 48, 51]]),
 array([[ 9, 12, 15],
        [36, 39, 42],
        [63, 66, 69]]),
 array([[ 3, 12, 21],
        [30, 39, 48],
        [57, 66, 75]]))

**Continuing...**