<a href="https://www.kaggle.com/code/sagorkumarmitra/numpy-walkthrough?scriptVersionId=140399059" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np

# The N-dimensional array (ndarray)

**A 2-dimensional array of size 2 x 3, composed of 4-byte integer elements:**

In [2]:
x=np.array([[1,2,3],[4,5,6]],np.int32)

In [3]:
type(x)

numpy.ndarray

In [4]:
x.shape

(2, 3)

In [5]:
x.dtype

dtype('int32')

In [6]:
x[1,2]

6

In [7]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [8]:
y=x[:,1]

In [9]:
y

array([2, 5], dtype=int32)

In [10]:
y[0]=9

**Memory layout**

In [11]:
x #ndarray

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [12]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [13]:
x.shape

(2, 3)

In [14]:
x.strides

(12, 4)

In [15]:
x.ndim

2

In [16]:
x.data

In [17]:
x.size

6

In [18]:
x.itemsize

4

In [19]:
x.nbytes

24

In [20]:
x.base

In [21]:
x.dtype

dtype('int32')

In [22]:
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [23]:
x.T

array([[1, 4],
       [9, 5],
       [3, 6]], dtype=int32)

In [24]:
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [25]:
x.real

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [26]:
x.imag

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [27]:
x.flat

In [28]:
x.ctypes

In [29]:
x.tolist()

[[1, 9, 3], [4, 5, 6]]

In [30]:
x.copy()

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [31]:
x.view()

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [32]:
x.fill(0)

In [33]:
x

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [34]:
x=np.array([[1,2,3],[4,5,6],[5,6,7]],np.int32)

**A 3-dimensional array of size 3 x 3 x 3, summed over each of its three axes**

In [35]:
x=np.arange(27)

In [36]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [37]:
x=np.arange(27).reshape(3,3,3)

In [38]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [39]:
x.sum(axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [40]:
x.sum(0),x.sum(1),x.sum(2)

(array([[27, 30, 33],
        [36, 39, 42],
        [45, 48, 51]]),
 array([[ 9, 12, 15],
        [36, 39, 42],
        [63, 66, 69]]),
 array([[ 3, 12, 21],
        [30, 39, 48],
        [57, 66, 75]]))

**class numpy.ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)**

In [41]:
# If buffer is None, then only shape, dtype, and order are used
np.ndarray(shape=(2,2),dtype=float,order='F')

array([[4.82342444e-310, 4.82342467e-310],
       [0.00000000e+000, 4.82342473e-310]])

In [42]:
# If buffer is an object exposing the buffer interface, then all keywords are interpreted.

np.ndarray((2,),buffer=np.array([1,2,3]),offset=np.int_().itemsize,dtype=int)

array([2, 3])

**ndarray.T**

In [43]:
a=np.array([[1,2],[3,4]])

In [44]:
a

array([[1, 2],
       [3, 4]])

In [45]:
a.T

array([[1, 3],
       [2, 4]])

In [46]:
a=np.array([1,2,3,4])

In [47]:
a

array([1, 2, 3, 4])

In [48]:
a.T

array([1, 2, 3, 4])

**convert a 1-D array into a 2-D column vector**

In [49]:
a_2d=a[:, np.newaxis]

In [50]:
a_2d.T

array([[1, 2, 3, 4]])

**If axes are not provided, then transpose(a).shape == a.shape[::-1]**

In [51]:
b=np.array([[1,2],[3,4]])

In [52]:
b

array([[1, 2],
       [3, 4]])

In [53]:
np.transpose(a).shape

(4,)

In [54]:
a.shape[::-1]

(4,)

In [55]:
a=np.ones((1,2,3))

In [56]:
np.transpose(a,(1,0,2)).shape

(2, 1, 3)

In [57]:
a = np.ones((2, 3, 4, 5))

In [58]:
a

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [59]:
np.transpose(a).shape

(5, 4, 3, 2)

**numpy.reshape**

In [60]:
a=np.arange(6)

In [61]:
a

array([0, 1, 2, 3, 4, 5])

In [62]:
a=a.reshape((3,2))

In [63]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [64]:
np.reshape(a,(2,3)) # C-like index ordering

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
np.reshape(np.ravel(a),(2,3)) # equivalent to C ravel then C reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
np.reshape(a, (2, 3), order='F') # Fortran-like index ordering

array([[0, 4, 3],
       [2, 1, 5]])

In [67]:
np.reshape(np.ravel(a, order='F'), (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [68]:
a = np.array([[1,2,3], [4,5,6]])

In [69]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [71]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [72]:
np.reshape(a, (3,-1))       # the unspecified value is inferred to be 2

array([[1, 2],
       [3, 4],
       [5, 6]])

**Continuing...**